# Generated by Django 5.2.1 on 2025-05-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0002_delete_selfassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Оценка')),
                ('comments', models.TextField(verbose_name='Комментарии')),
                ('areas_to_improve', models.TextField(verbose_name='Области для улучшения')),
                ('created_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessment', to='goals.goal', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Самооценка',
                'verbose_name_plural': 'Самооценки',
                'db_table': 'goals_self_assessments',
            },
        ),
    ]
