# Generated by Django 5.2.1 on 2025-05-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('expected_results', models.TextField(verbose_name='Ожидаемые результаты')),
                ('start_period', models.DateField(verbose_name='Начало периода')),
                ('end_period', models.DateField(verbose_name='Конец периода')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_approval', 'На согласовании'), ('approved', 'Согласовано'), ('in_progress', 'В процессе'), ('pending_assessment', 'Ожидает оценки'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dttm', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accounts.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'db_table': 'goals',
                'ordering': ['-created_dttm'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание прогресса')),
                ('created_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='goals.goal', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Запись о прогрессе',
                'verbose_name_plural': 'Записи о прогрессе',
                'db_table': 'goals_progresses',
                'ordering': ['-created_dttm'],
            },
        ),
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Оценка')),
                ('comments', models.TextField(verbose_name='Комментарии')),
                ('areas_to_improve', models.TextField(verbose_name='Области для улучшения')),
                ('created_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessment', to='goals.goal', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Самооценка',
                'verbose_name_plural': 'Самооценки',
                'db_table': 'goals_self_assessments',
            },
        ),
    ]
