# Generated by Django 5.2.1 on 2025-05-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelfAssessment',
        ),
    ]
